config/routes.rb
Rails.application.routes.draw do
   

    root to:'tasks#index'
    resources :tasks
    
     
     get 'login', to: 'sessions#new'
     post 'login', to: 'sessions#create'
     delete 'logout',to:'sessions#destroy'
    
     
    
    get 'signup', to: 'users#new'
   
   resources :users,only:[ :new, :create]
   
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    validates:content,presence: true, length:{maximum:255}
    validates :status,presence: true, length:{maximum:10}
end

app/models/user.rb
class User < ApplicationRecord
    before_save{self.email.downcase!}
    validates:name,presence:true,length:{maximum:50}
    validates:email,presence:true,length:{maximum:255},
              format:{ with:/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
              uniqueness:{ case_sensitive:false }
    has_secure_password
    
    has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    include SessionsHelper
    
    private
    
    def require_user_logged_in
        unless logged_in?
        redirect_to login_url
    end
    end
    
    def counts(user)
        @count_tasks = user.tasks.count
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email,password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to tasks_url
    else
      flash.now[:danger] ='ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to tasks_url
  end



private


def login(email,password)
  @user=User.find_by(email: email)
  if @user && @user.authenticate(password)
    session[:user_id]=@user.id
    return true
  else
    return false
  end
end



end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user,only:[:destroy,:show,:edit,:update]
    
  def index
        if logged_in?
        @task= current_user.tasks.build
        @tasks= current_user.tasks.order(id: :desc).page(params[:page])
        end
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
      @task = Task.new
  end

  def create
      @task = current_user.tasks.build(task_params)
      
      if @task.save
          flash[:success]='タスクが正常に登録されました。'
          redirect_to tasks_url
      else
          flash.now[:danger]='タスクが正常に登録されませんでした。'
          render 'tasks/new'
      end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
      @task = Task.find(params[:id])
      if @task.update(task_params)
          flash[:success]='タスクは正常に更新されました。'
          redirect_to task_url
      else
          flash.now[:danger]='タスクは更新されませんでした。'
          render 'users/edit'
      end
  end

  def destroy
      @task = Task.find(params[:id])
      @task.destroy
      
      flash[:success]='タスクは正常に削除されました。'
      redirect_to task_url
  end



private

  def correct_user
    @task = current_user.tasks.find_by(id:params[:id])
    unless @task
    redirect_to root_url
    end
  end

  def task_params
      params.require(:task).permit(:content,:status)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only:[:index,:show]
  
  def index
    @users = User.order(id: :desc).page(params[:page]).per(25)
  end

  def show
    @user =User.find(params[:id])
    @tasks = @user.tasks.order(id: :desc).page(params[:page])
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success]='ユーザを登録しました。'
      redirect_to tasks_url
    else
      flash.now[:danger]='ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  def followings
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page])
    counts(@user)
  end

  def followers
  @user = User.find(params[:id])
  @followers = @user.followers.page(params[:page])
  end

end


private

def user_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||=User.find_by(id:session[:user_id])
    end
    
    def logged_in?
        !!current_user
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_url(user,options={size:80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size=options[:size]
        "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    end
end

app/views/layouts/_error_tasks.html.erb
<% if model.errors.any? %>
<div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
        <% model.errors.full_messages.each do |task| %>
            <li><%= task %></li>
            <% end %>
            
    </ul>
</div>
<% end %>

app/views/layouts/_flash_tasks.html.erb
<% flash.each do |task_type, task | %>
 <div class="alert alert-<%= task_type %>"><<%= task %></div>
 <% end %>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>KadaiTasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/flash_tasks' %>
   
    
    <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/___new.html.erb
<h1>タスク新規作成ページ</h1>

<%= render 'form', task: @task %>

app/views/tasks/_form.html.erb
<div class="row">
  <div class="col-6">
    
<%= form_with(model: task, local: true) do |f| %>
  <% if task.errors.any? %>
    <div id="error_explanation" class="alert alert-warning">
      <ul class="mb-0">
        <% task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-group">
  <%= f.label :status, 'ステータス' %>
  <%= f.text_field :status, class:'form-control' %>
</div>
<div class="form-group">
  <%= f.label :content, 'タスク' %>
  <%= f.text_field :content, class:'form-control' %>
</div>
  <%= f.submit '登録', class:'btn btn-primary' %>
<% end %>
    
  </div>
</div>

app/views/tasks/_tasks.html.erb
<h1>タスク一覧</h1>

<% if @tasks.any? %>
<table class="table table-striped">
    <thead>
        <tr>
            <th>id</th>
            <th>ステータス</th>
            <th>タスク</th>
            
        </tr>
    </thead>
    <tbody>
        <% @tasks.each do |task| %>
        <tr>
            <td><%= link_to task.id, task %></td>
            <td><%= task.status %></td>
            <td><%= task.content %></td>
        </tr>
        <% end %>
        
    </tbody>
</table>
<%= paginate tasks %>
</div>
<% end %>

<%= link_to '新規タスク登録',new_task_path,class:"btn btn-primary" %>

app/views/tasks/edit.html.erb
<h1>id: <%= @task.id %> のタスク編集ページ</h1>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<% if logged_in? %>
<p>ログイン完了ユーザ：<%= current_user.name %></p>

<h1>タスク一覧</h1>

<table class="table table-striped" >
    <thead>
        <tr>
            <th>id</th>
            <th>ステータス</th>
            <th>タスク</th>
        </tr>
    </thead>
    <tbody>
        <% @tasks.each do |task| %>
        <tr>
            <td><%= link_to task.id, task %></td>
            <td><%= task.status %></td>
            <td><%= task.content %></td>
        </tr>
        <% end %>
    </tbody>
</table>


<% else %>
   redirect_to tasks_url
<% end %>
<%= link_to '新規タスクの登録', new_task_path, class: "btn btn-primary" %>
<%= link_to 'Logout', logout_path, method: :delete ,class: 'btn btn-danger' %>

app/views/tasks/new.html.erb
<h1>タスク新規作成ページ</h1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1>id: <%= @task.id %> のメッセージ詳細ページ</h1>

<table class="table table-bordered">
    <tr>
        <th>id</th>
        <td><%= @task.id %></td>
    </tr>
    <tr>
        <th>ステータス</th>
        <td><%= @task.status %></td>
    </tr>
    <tr>
        <th><タスク</th>
        <td><%= @task.content %></td>
    </tr>
</table>


<%= link_to '一覧に戻る', tasks_path %>
<%= link_to 'このメッセージを編集する', edit_task_path(@task),class:'btn btn-light' %>
<%= link_to 'このメッセージを削除する', @task, method: :delete, data: { confirm: '本当に削除してよろしいですか？' },class: 'btn btn-danger' %>

app/views/users/_users.html.erb
<ul class="list-unstyled">
    <% users.each do |user| %>
    <li><%= link_to task.id, task %>:<%= task.status %><%= task.content %></li>

    <% end %>
</ul>
<%= paginate users %>

app/views/users/index.html.erb
<%= render 'users',users:@users %>

app/views/users/new.html.erb
<div class="text-center">
    <h1>Sign up</h1>
</div>

<div class="row">
    <div class="col-sm-6 offset-sm-3">
        
        <%= form_with(model: @user, local:true) do |f|%>
        <%= render 'layouts/error_tasks',model: f.object %>
            
            <div class="form-group">
            <%= f.label :name, 'Name' %>
            <%= f.text_field :name, class: 'form-control' %>
    </div>
    
    <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email,class: 'form-control' %>
    </div>
    
    <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class:'form-control' %>
    </div>
    
    <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    
    <%= f.submit 'Sign up', class:'btn btn-primary btn-block' %>
    <% end %>
    </div>
    

</div>

app/views/users/show.html.erb
    <%= render 'users', users: @users %>